[package]
name = "rustcracker"
version = "1.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Xue Haonan <xuehaonan27@gmail.com>"]
description = "A crate for communicating with firecracker for the development of PKU-cloud."
repository = "https://github.com/xuehaonan27/rustcracker"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.28" }
serde = { version = "1.0.195", features = ["serde_derive"] }
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["process", "macros", "fs"] }
async-channel = "2.1.1"
nix = { version = "0.27.1", features = ["fs", "user", "signal"] }
log = "0.4.20"
env_logger = "0.10.1"
uuid = { version = "1.6.1", features = ["v4", "fast-rng"] }
hyperlocal = "0.8.0"
thiserror = "1.0.56"
run_script = "0.10.1"

[[bin]]
name = "rebuild"

[[bin]]
name = "exhausting"

[[bin]]
name = "benchmark"

[[bin]]
name = "attach_detach"

[[bin]]
name = "jailing_machine"