use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize)]
pub enum Signal {
    SIGHUP,
    SIGINT,
    SIGQUIT,
    SIGILL,
    SIGTRAP,
    SIGABRT,
    SIGBUS,
    SIGFPE,
    SIGKILL,
    SIGUSR1,
    SIGSEGV,
    SIGUSR2,
    SIGPIPE,
    SIGALRM,
    SIGTERM,
    // SIGSTKFLT,
    SIGCHLD,
    SIGCONT,
    SIGSTOP,
    SIGTSTP,
    SIGTTIN,
    SIGTTOU,
    SIGURG,
    SIGXCPU,
    SIGXFSZ,
    SIGVTALRM,
    SIGPROF,
    SIGWINCH,
    SIGIO,
    // SIGPWR,
    SIGSYS,
}

impl Into<nix::sys::signal::Signal> for Signal {
    fn into(self) -> nix::sys::signal::Signal {
        match self {
            Signal::SIGHUP => nix::sys::signal::SIGHUP,
            Signal::SIGINT => nix::sys::signal::SIGINT,
            Signal::SIGQUIT => nix::sys::signal::SIGQUIT,
            Signal::SIGILL => nix::sys::signal::SIGILL,
            Signal::SIGTRAP => nix::sys::signal::SIGTRAP,
            Signal::SIGABRT => nix::sys::signal::SIGABRT,
            Signal::SIGBUS => nix::sys::signal::SIGBUS,
            Signal::SIGFPE => nix::sys::signal::SIGFPE,
            Signal::SIGKILL => nix::sys::signal::SIGKILL,
            Signal::SIGUSR1 => nix::sys::signal::SIGUSR1,
            Signal::SIGSEGV => nix::sys::signal::SIGSEGV,
            Signal::SIGUSR2 => nix::sys::signal::SIGUSR2,
            Signal::SIGPIPE => nix::sys::signal::SIGPIPE,
            Signal::SIGALRM => nix::sys::signal::SIGALRM,
            Signal::SIGTERM => nix::sys::signal::SIGTERM,
            // Signal::SIGSTKFLT => nix::sys::signal::SIGSTK
            Signal::SIGCHLD => nix::sys::signal::SIGCHLD,
            Signal::SIGCONT => nix::sys::signal::SIGCONT,
            Signal::SIGSTOP => nix::sys::signal::SIGSTOP,
            Signal::SIGTSTP => nix::sys::signal::SIGTSTP,
            Signal::SIGTTIN => nix::sys::signal::SIGTTIN,
            Signal::SIGTTOU => nix::sys::signal::SIGTTOU,
            Signal::SIGURG => nix::sys::signal::SIGURG,
            Signal::SIGXCPU => nix::sys::signal::SIGXCPU,
            Signal::SIGXFSZ => nix::sys::signal::SIGXFSZ,
            Signal::SIGVTALRM => nix::sys::signal::SIGVTALRM,
            Signal::SIGPROF => nix::sys::signal::SIGPROF,
            Signal::SIGWINCH => nix::sys::signal::SIGWINCH,
            Signal::SIGIO => nix::sys::signal::SIGIO,
            // Signal::SIGPWR => nix::sys::signal::SIGPWR,
            Signal::SIGSYS => nix::sys::signal::SIGSYS,
        }
    }
}
